src/Entity/Publication.php
<?php

namespace App\Entity;

use App\Repository\PublicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PublicationRepository::class)]
class Publication
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Type Cannot be empty")]
    private ?string $type = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Titre Cannot be empty")]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Description cannot be empty")]
    private ?string $description = null;

    #[ORM\Column(length: 3000)]
    #[Assert\NotBlank(message: "Image cannot be empty")]
    private ?string $image = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: "Video Cannot be empty")]
    private ?string $video = null;

    #[ORM\ManyToOne(inversedBy: 'publications')]
    #[Assert\NotBlank(message: "id_user Cannot be empty")]
    private ?Users $id_user = null;

    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'id_pub')]
    private Collection $commentaires;

    #[ORM\OneToMany(targetEntity: React::class, mappedBy: 'id_pub')]
    private Collection $reacts;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->reacts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): static
    {
        $this->video = $video;

        return $this;
    }

    public function getIdUser(): ?Users
    {
        return $this->id_user;
    }

    public function setIdUser(?Users $id_user): static
    {
        $this->id_user = $id_user;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setIdPub($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getIdPub() === $this) {
                $commentaire->setIdPub(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, React>
     */
    public function getReacts(): Collection
    {
        return $this->reacts;
    }

    public function addReact(React $react): static
    {
        if (!$this->reacts->contains($react)) {
            $this->reacts->add($react);
            $react->setIdPub($this);
        }

        return $this;
    }

    public function removeReact(React $react): static
    {
        if ($this->reacts->removeElement($react)) {
            // set the owning side to null (unless already changed)
            if ($react->getIdPub() === $this) {
                $react->setIdPub(null);
            }
        }

        return $this;
    }
}

src/Form/PublicationType.php
<?php

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType; 
use App\Entity\Users; 
use App\Entity\Commentaire;
use App\Form\CommentaireType; 
use App\Entity\Publication;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PublicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Nutrition' => 'Nutrition',
                    'Progrés' => 'Progrés',
                ],
                'placeholder' => 'Choose a type', 
                'required' => true, 
            ])
            ->add('titre')
            ->add('description')
            ->add('image', FileType::class, [
                'label' => 'Image',
                'required' => false,
                'data_class' => null, 
            ])
            ->add('video')
          
            ->add('id_user', EntityType::class, [
                'class' => Users::class, // Set the class to the User entity
                'choice_label' => 'email',
                'label'=> 'User', // Set the property to display in the dropdown
                'placeholder' => 'Select a user', // Optional: Add a placeholder
                'required' => true, 
                'disabled' => 'disabled',
                
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Publication::class,
        ]);
    }
}

src/Controller/PublicationController.php
<?php

namespace App\Controller;

use App\Entity\Publication;
use App\Form\PublicationType;
use App\Repository\PublicationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\FormView;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use Symfony\Component\HttpFoundation\RedirectResponse;


#[Route('publication')]
class PublicationController extends AbstractController
{
    #[Route('/', name: 'app_publication_index', methods: ['GET'])]
    public function index(PublicationRepository $publicationRepository, Request $request): Response
    {
        $type = $request->query->get('type');

        // Check if the type query parameter is set and filter publications accordingly
        if ($type && in_array($type, ['Nutrition', 'Progrés'])) {
            $publications = $publicationRepository->findBy(['type' => $type]);
        } else {
            $publications = $publicationRepository->findAll();
        }

        return $this->render('front/publication/index.html.twig', [
            'publications' => $publications,
        ]);
    }

   

    #[Route('/new', name: 'app_publication_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $publication = new Publication();
        $form = $this->createForm(PublicationType::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image')->getData();
            if ($imageFile) {
                $imageName = md5(uniqid()) . '.' . $imageFile->guessExtension();
                $imageFile->move(
                    $this->getParameter('kernel.project_dir') . '/public/uploads/images',
                    $imageName
                );
                $publication->setImage('/uploads/images/' . $imageName);
            }

            $entityManager->persist($publication);
            $entityManager->flush();

            return $this->redirectToRoute('app_publication_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('front/publication/new.html.twig', [
            'publication' => $publication,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_publication_show', methods: ['GET', 'POST'])]
public function show(Request $request, Publication $publication, EntityManagerInterface $entityManager): Response
{
    $commentaire = new Commentaire();
    $commentForm = $this->createForm(CommentaireType::class, $commentaire);
    $commentForm->handleRequest($request);

    // Check if the user is authenticated before setting the id_user
    $user = $this->getUser();
    if ($user instanceof User) {
        $commentaire->setIdUser($user);
    }

    // Automatically set the id_pub to the id of the current publication
    $commentaire->setIdPub($publication);

    if ($commentForm->isSubmitted() && $commentForm->isValid()) {
        // Persist the comment
        $entityManager->persist($commentaire);
        $entityManager->flush();

        // Redirect back to the publication page after submitting the comment
        return $this->redirectToRoute('app_publication_show', ['id' => $publication->getId()]);
    }

    return $this->render('front/publication/show.html.twig', [
        'publication' => $publication,
        'commentForm' => $commentForm->createView(),
    ]);
}



    #[Route('/{id}/edit', name: 'app_publication_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Publication $publication, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PublicationType::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image')->getData();
            if ($imageFile) {
                $imageName = md5(uniqid()) . '.' . $imageFile->guessExtension();
                $imageFile->move(
                    $this->getParameter('kernel.project_dir') . '/public/uploads/images',
                    $imageName
                );
                $publication->setImage('/uploads/images/' . $imageName);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_publication_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('front/publication/edit.html.twig', [
            'publication' => $publication,
            'form' => $form->createView(),
        ]);
    }

  
    #[Route('/publication/{id}', name: 'app_publication_delete', methods: ['POST'])]
    public function delete(Request $request, Publication $publication, EntityManagerInterface $entityManager): RedirectResponse
    {
        if (!$publication) {
            throw $this->createNotFoundException('Publication not found');
        }

        if ($this->isCsrfTokenValid('delete' . $publication->getId(), $request->request->get('_token'))) {
            $entityManager->remove($publication);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_publication_index');
    }
    

    
    
}

templates/front/publication/_delete_form.html.twig
<form method="post" action="{{ path('app_publication_delete', {'id': publication.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ publication.id) }}">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

templates/front/publication/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{ form_label(form.type) }}
        {{ form_widget(form.type) }}
    </div>

    <div class="form-group">
        {{ form_label(form.titre) }}
        {{ form_widget(form.titre) }}
    </div>

    <div class="form-group">
        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
    </div>

    <div class="form-group">
        {{ form_label(form.image) }}
        {{ form_widget(form.image, {'attr': {'class': 'form-control-file'}}) }}
    </div>

    <div class="form-group">
        {{ form_label(form.video) }}
        {{ form_widget(form.video) }}
    </div>

    <div class="form-group">
        {{ form_label(form.id_user) }}
        {{ form_widget(form.id_user, {'attr': {'class': 'form-control'}}) }}
    </div>

    <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/front/publication/edit.html.twig
{% extends 'front/base.html.twig' %}

{% block title %}Edit Publication{% endblock %}

{% block body %}

<br><br><br><br><br>
<div class="container">
    <h1>Edit Publication</h1>

    <div class="form-container">
        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}

        <div class="form-group">
            {{ form_label(form.type) }}
            {{ form_widget(form.type, {'attr': {'class': 'form-control'}}) }}
            {% if form_errors(form.type) %}
                <div class="alert alert-danger">
                    {{ form_errors(form.type) }}
                </div>
            {% endif %}
            
        </div>

        <div class="form-group">
            {{ form_label(form.titre) }}
            {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
            {% if form_errors(form.titre) %}
                <div class="alert alert-danger">
                    {{ form_errors(form.titre) }}
                </div>
            {% endif %}
        </div>
        
        <div class="form-group">
            {{ form_label(form.description) }}
            {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
            {% if form_errors(form.description) %}
                <div class="alert alert-danger">
                    {{ form_errors(form.description) }}
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form_label(form.image) }}
            {{ form_widget(form.image, {'attr': {'class': 'form-control'}}) }}
            {% if form_errors(form.image) %}
                <div class="alert alert-danger">
                    {{ form_errors(form.image) }}
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form_label(form.video) }}
            {{ form_widget(form.video, {'attr': {'class': 'form-control'}}) }}
            {% if form_errors(form.video) %}
                <div class="alert alert-danger">
                    {{ form_errors(form.video) }}
                </div>
            {% endif %}
        </div>

        <div class="form-group">
            {{ form_label(form.id_user) }}
            {{ form_widget(form.id_user, {'attr': {'class': 'form-control'}}) }}
            {% if form_errors(form.id_user) %}
                <div class="alert alert-danger">
                    {{ form_errors(form.id_user) }}
                </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary">Update</button>

        {{ form_end(form) }}
    </div>

    <a href="{{ path('app_publication_index') }}" class="back-link">Back to List</a>

</div>


<br><br><br><br><br><br><br><br><br><br><br>
    

{% endblock %}

templates/front/publication/index.html.twig
{% extends 'front/base.html.twig' %}

{% block title %}Publication{% endblock %}

{% block stylesheets %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">
    <style>
        body {
            background-image: url('/front/img/background.jpg');
            background-size: cover;
            background-position: center;
        }

        .card-body {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100%;
        }

        #header {
            background-color: white;
            padding: 10px 0;
        }

        .card-body img {
            width: 200px;
            height: 200px;
            object-fit: cover;
        }
    </style>
{% endblock %}

{% block body %}


    

    <div style="text-align: center; margin-top: 100px;">
        <h1>Publications</h1>
    </div>

    <div class="container">

      <form id="sortForm" method="GET" action="{{ path('app_publication_index') }}" class="mb-3">
    <div class="input-group">
        <label class="input-group-text" for="type_select">Filter by:</label>
        <select class="form-select" id="type_select" name="type" style="width: 150px;"> <!-- Adjust the width as needed -->
            <option value="" {% if not app.request.get('type') %}selected{% endif %}>All</option>
            <option value="Nutrition" {% if app.request.get('type') == 'Nutrition' %}selected{% endif %}>Nutrition</option>
            <option value="Progrés" {% if app.request.get('type') == 'Progrés' %}selected{% endif %}>Progrés</option>
        </select>
    </div>
</form>

<script>
    document.getElementById('type_select').addEventListener('change', function() {
        document.getElementById('sortForm').submit();
    });
</script>

    

      <a href="{{ path('app_publication_new') }}" class="btn btn-primary">Create new</a>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for publication in publications %}
                <div class="col">
                    <div class="card">
                        <img src="{{ asset(publication.image) }}" class="card-img-top" alt="Publication Image" width="200" height="200">
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ publication.titre }}</h5>
                            <p class="card-text">{{ publication.description }}</p>
                            <a href="{{ path('app_publication_show', {'id': publication.id}) }}" class="btn btn-primary">Read more</a>
                        </div>
                    </div>
                </div>
            {% else %}
                <p>No publications available</p>
            {% endfor %}
        </div>
    </div>

    
<br><br><br><br><br><br><br><br>
   
{% endblock %}

templates/front/publication/new.html.twig
{% extends 'front/base.html.twig' %}

{% block title %}
    New Publication
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/publication.css') }}">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            text-align: center;
        }

        .header {
            margin-bottom: 30px; /* Adjust spacing between header and form container */
        }

        .form-container {
            width: 400px; /* Adjust width as needed */
            margin: 0 auto;
        }
    </style>
{% endblock %}

{% block body %}

<br><br><br><br><br>

    <div class="container">
        <h1>Create New Publication</h1>

        <div class="form-container">
            {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}

            <div class="form-group">
                {{ form_label(form.type) }}
                {{ form_widget(form.type, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.type) %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.type) }}
                    </div>
                {% endif %}
                
            </div>

            <div class="form-group">
                {{ form_label(form.titre) }}
                {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
            
                {% if form_errors(form.titre) %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.titre) }}
                    </div>
                {% endif %}
            </div>
            
            <div class="form-group">
                {{ form_label(form.description) }}
                {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.description) %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.description) }}
                    </div>
                {% endif %}
            </div>

            <div class="form-group">
                {{ form_label(form.image) }}
                {{ form_widget(form.image, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.image) %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.image) }}
                    </div>
                {% endif %}
            </div>

            <div class="form-group">
                {{ form_label(form.video) }}
                {{ form_widget(form.video, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.video) %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.video) }}
                    </div>
                {% endif %}
            </div>

            <div class="form-group">
                {{ form_label(form.id_user) }}
                {{ form_widget(form.id_user, {'attr': {'class': 'form-control'}}) }}
                {% if form_errors(form.id_user) %}
                    <div class="alert alert-danger">
                        {{ form_errors(form.id_user) }}
                    </div>
                {% endif %}
            </div>

            <button type="submit" class="btn btn-primary">Save</button>

            {{ form_end(form) }}
        </div>

        <a href="{{ path('app_publication_index') }}" class="back-link">Back to List</a>
    </div>

 
   
{% endblock %}

templates/front/publication/show.html.twig
{% extends 'front/base.html.twig' %}

{% block title %}Publication{% endblock %}

{% block body %}

<br><br><br><br><br>
    <div class="container">
        <h1 class="text-center">Publication</h1>

        <div class="text-center">
            <img src="{{ publication.image }}" alt="Publication Image" class="img-fluid" style="max-width: 1000px; height: auto;">
        </div>

        <div class="text-center mt-3">
            <div>
                <h2>{{ publication.titre }}</h2>
                <p>{{ publication.description }}</p>
                <br><br>
                {{ include('front/publication/_delete_form.html.twig', { 'publication': publication }) }}

            </div>
        </div>
        

        <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publication</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">
</head>
<body>

<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8">

            <style>
                /* Your CSS styles here */
                body {
                    background-color: #f7f6f6;
                }

                .card {
                    border: none;
                    box-shadow: 5px 6px 6px 2px #e9ecef;
                    border-radius: 4px;
                }

                .dots {
                    height: 4px;
                    width: 4px;
                    margin-bottom: 2px;
                    background-color: #bbb;
                    border-radius: 50%;
                    display: inline-block;
                }

                .badge {
                    padding: 7px;
                    padding-right: 9px;
                    padding-left: 16px;
                    box-shadow: 5px 6px 6px 2px #e9ecef;
                }

                .user-img {
                    margin-top: 4px;
                }

                .check-icon {
                    font-size: 17px;
                    color: #c3bfbf;
                    top: 1px;
                    position: relative;
                    margin-left: 3px;
                }

                .form-check-input {
                    margin-top: 6px;
                    margin-left: -24px !important;
                    cursor: pointer;
                }

                .form-check-input:focus {
                    box-shadow: none;
                }

                .icons i {
                    margin-left: 8px;
                }

                .reply {
                    margin-left: 12px;
                }

                .reply small {
                    color: #b7b4b4;
                }

                .reply small:hover {
                    color: green;
                    cursor: pointer;
                }
            </style>

            <div class="headings d-flex justify-content-between align-items-center mb-3">
                <h5>Comments</h5>
                <div class="buttons">
                    <span class="badge bg-white d-flex flex-row align-items-center">
                        <span class="text-primary">Comments</span>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="toggleComments" checked>
                        </div>
                    </span>
                </div>
            </div>

            <ul class="list-group" id="commentsList">
                {% for commentaire in publication.commentaires %}
                    <li class="list-group-item">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="user d-flex flex-row align-items-center">
                                <span><small class="font-weight-bold text-primary">{{ commentaire.idUser.nom }}</small>: {{ commentaire.contenu }}</span>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <div class="text-center mt-3">
                <a href="{{ path('app_publication_index') }}" class="btn btn-primary">Back to List</a>
                <a href="{{ path('app_publication_edit', {'id': publication.id}) }}" class="btn btn-secondary">Edit</a>
            </div>

            <div class="container mt-5">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-8">
                        <h5>Add a Comment</h5>
                        
                        {{ form_start(commentForm, {'attr': {'novalidate': 'novalidate'}}) }}

                        <div class="form-group">
                            {{ form_label(commentForm.contenu, null, {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_widget(commentForm.contenu, {'attr': {'class': 'form-control'}}) }}
                            {% if form_errors(commentForm.contenu) %}
                                <div class="alert alert-danger">
                                    {{ form_errors(commentForm.contenu) }}
                                </div>
                            {% endif %}
                        </div>
                        
                        <div class="form-group">
                            {{ form_label(commentForm.id_user, 'Nom de l utilisateur', {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_widget(commentForm.id_user, {'attr': {'class': 'form-control'}}) }}
                            {% if form_errors(commentForm.id_user) %}
                                <div class="alert alert-danger">
                                    {{ form_errors(commentForm.id_user) }}
                                </div>
                            {% endif %}
                        </div>
                        
                        <div class="form-group" style="display: none;">
                            {# Hidden field for id_pub #}
                            {{ form_label(commentForm.id_pub, 'Publication', {'label_attr': {'class': 'control-label'}}) }}
                            {{ form_widget(commentForm.id_pub, {'attr': {'class': 'form-control'}}) }}
                            {% if form_errors(commentForm.id_pub) %}
                                <div class="alert alert-danger">
                                    {{ form_errors(commentForm.id_pub) }}
                                </div>
                            {% endif %}
                        </div>
                        
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                        
                        {{ form_end(commentForm) }}
                        

                    </div>
                </div>
            </div>

           


            <script>
                const toggleComments = document.getElementById('toggleComments');
                const commentsList = document.getElementById('commentsList');

                toggleComments.addEventListener('change', function() {
                    if (toggleComments.checked) {
                        commentsList.style.display = 'block';
                    } else {
                        commentsList.style.display = 'none';
                    }
                });
            </script>
        </div>
    </div>
</div>



</body>
<br><br><br><br><br><br><br><br><br><br><br>
   
</html>

        
        
        
        
{% endblock %}